Verbose logging only if in debug mode
home-assistant/plugin-audio pull request #112
Opened 2022-07-25 17:11 UTC by mdegat01

Only do verbose logging if supervisor is in debug mode, otherwise drop `-vvv` from command.

Parent PR: https://github.com/home-assistant/supervisor/pull/3752

Supercedes #85 

Fixes #57
Fixes #56

2022-07-27 08:36 UTC, agners requested changes

2022-07-27 08:36 UTC, agners commented on rootfs/etc/services.d/pulseaudio/run
> +if [ "$debug" == 'true']; then
```suggestion
if [ "$debug" = "true" ]; then
```

Space before `]` seems to be required. Single `=` is more POSIX. Quotes probably doesn't matter, but is nicer IMHO.

2022-07-28 09:00 UTC, agners approved these changes

2022-07-28 09:02 UTC, pvizeli commented on rootfs/etc/services.d/pulseaudio/run
> +debug="$(jq '.debug' /config/plugin_audio.json)"
Let's use bashio

2022-07-28 09:32 UTC, pvizeli commented on rootfs/etc/services.d/pulseaudio/run
> +if [ "$debug" = "true" ]; then
for this too

2022-07-28 15:26 UTC, merged